import type {
  Customer,
  ListPrice,
  PriceTable,
  PriceTableVersion,
  Product,
  ProductGroup,
  Seller,
} from '@salesforce/domain';
import { canonicalDecimal, fixedToDecimal } from '../decimal.js';
import {
  DEMO_DERIVED_TABLE_CODE,
  DEMO_FALLBACK_TABLE_CODE,
  DEMO_MAIN_TABLE_CODE,
} from './demo-configuration.js';
import { Prng } from './prng.js';

/**
 * SYNTHETIC demo dataset of an industrial distributor, generated deterministically from a seed.
 * Nothing here is real: company and person names are invented, tax ids carry deliberately wrong
 * check digits (and a `9999`/`999` marker), and there is no phone, e-mail or address. Provenance:
 * generated by this module (slice 1, 2026-09-18); no Sankhya capture was used or consulted.
 *
 * The dataset only uses the Sales Force-shaped domain types, so it cannot express ERP-only facts
 * (city/UF, manager code on a seller, per-version percentages).
 */
export interface DemoSellerManagerLink {
  readonly sellerCode: number;
  /** `null` = has no manager (top of the hierarchy). The domain `Seller` has no manager field yet (R35/R36). */
  readonly managerSellerCode: number | null;
}

export interface DemoDataset {
  readonly sellers: readonly Seller[];
  readonly sellerManagerLinks: readonly DemoSellerManagerLink[];
  readonly customers: readonly Customer[];
  readonly productGroups: readonly ProductGroup[];
  readonly products: readonly Product[];
  readonly priceTables: readonly PriceTable[];
  readonly priceTableVersions: readonly PriceTableVersion[];
  readonly listPrices: readonly ListPrice[];
}

export const DEMO_SEED = 0x5a1e5;

/** Two stored versions per table (F-39: superseded versions stay stored). All dates are in the past. */
export const DEMO_OLDER_VERSION_FROM = '2026-01-01T03:00:00.000Z';
export const DEMO_EFFECTIVE_VERSION_FROM = '2026-08-17T03:00:00.000Z';
const DEMO_FALLBACK_EFFECTIVE_FROM = '2026-08-03T03:00:00.000Z';

export const DEMO_SELLABLE_USAGE_CODES: readonly string[] = ['A', 'B'];

// ---- sellers ------------------------------------------------------------------------------------

const SELLER_NAMES = [
  'Helena Torvaldes',
  'Otavio Mirandel',
  'Beatriz Casterino',
  'Caetano Belfrago',
  'Dalila Orsanti',
  'Everaldo Vilmarin',
  'Fabiola Quadrante',
  'Gilmar Saltares',
  'Ivanildo Prudel',
  'Jussara Nevarro',
  'Leandro Ostrelli',
  'Marlene Fenzari',
] as const;

const INACTIVE_SELLER_CODE = 110;
const SELLER_FIRST_CODE = 101;

function buildSellers(): { sellers: Seller[]; links: DemoSellerManagerLink[] } {
  const sellers: Seller[] = SELLER_NAMES.map((name, index) => ({
    code: SELLER_FIRST_CODE + index,
    name,
    active: SELLER_FIRST_CODE + index !== INACTIVE_SELLER_CODE,
  }));
  // 101 and 102 are managers (no manager above); 103-106 report to 101; 107-112 report to 102.
  const links: DemoSellerManagerLink[] = sellers.map((seller) => ({
    sellerCode: seller.code,
    managerSellerCode: seller.code <= 102 ? null : seller.code <= 106 ? 101 : 102,
  }));
  return { sellers, links };
}

// ---- customers ----------------------------------------------------------------------------------

const GIVEN_NAMES = ['Alvaro', 'Berenice', 'Cirilo', 'Dagmar', 'Eustaquio', 'Fatima', 'Geraldo', 'Heloisa', 'Isidoro', 'Josefa', 'Lauro', 'Marilda', 'Nestor', 'Odete', 'Paulino', 'Quiteria', 'Rogerio', 'Sonia', 'Tadeu', 'Valdete'];
const SURNAMES = ['Arvelino', 'Bastarda', 'Cordovil', 'Dalmasso', 'Esperança', 'Falconieri', 'Guimarti', 'Hortelini', 'Imperial', 'Jaguaribe', 'Kalmar', 'Lacerdon', 'Montefiori', 'Nogarola', 'Orsolini', 'Pavanel', 'Ribamar', 'Sanfelice', 'Tramontin', 'Ulisses'];
const COMPANY_ROOTS = ['Corvato', 'Belmira', 'Tavenor', 'Ostrand', 'Melvora', 'Zaparo', 'Lindoro', 'Fontara', 'Pradexa', 'Nuvelar', 'Quitera', 'Arvenda', 'Bolsari', 'Cadrena', 'Dumarte', 'Elvasa', 'Gavirol', 'Hortelan', 'Ibertel', 'Jandaro', 'Kalvera', 'Lomarti', 'Mirasol', 'Norvela', 'Orlanda', 'Pertino', 'Quilmes', 'Rovanti', 'Salvora', 'Tarcival', 'Umbrata', 'Valdoro', 'Westina', 'Xandel', 'Yaramis', 'Zenobra'];
const COMPANY_SEGMENTS = ['Ferragens', 'Metalúrgica', 'Usinagem', 'Comercial', 'Distribuidora', 'Indústria', 'Manutenção', 'Serralheria', 'Construções', 'Autopeças', 'Máquinas', 'Embalagens', 'Caldeiraria', 'Elétrica', 'Hidráulica', 'Pneumática'];
const COMPANY_SUFFIXES = ['Ltda', 'S.A.', 'EPP', 'ME'];

const CUSTOMER_COUNT = 250;
const CUSTOMER_FIRST_CODE = 40001;
const CREDIT_STEPS = [0, 2500, 5000, 10000, 25000, 50000, 100000, 250000, 500000];

/** Wrong-on-purpose check digits: the first digit is always different from the correct one. */
function weightedDigit(digits: readonly number[], weights: readonly number[]): number {
  const sum = digits.reduce((acc, digit, index) => acc + digit * (weights[index] ?? 0), 0);
  const remainder = sum % 11;
  return remainder < 2 ? 0 : 11 - remainder;
}

function fakeCnpj(sequence: number): string {
  const base = `9999${String(sequence).padStart(4, '0')}0001`.split('').map(Number);
  const correct = weightedDigit(base, [5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2]);
  const first = (correct + 1) % 10;
  const second = weightedDigit([...base, first], [6, 5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2]);
  return `${base.join('')}${first}${second}`;
}

function fakeCpf(sequence: number): string {
  const base = `999${String(sequence).padStart(6, '0')}`.split('').map(Number);
  const correct = weightedDigit(base, [10, 9, 8, 7, 6, 5, 4, 3, 2]);
  const first = (correct + 1) % 10;
  const second = weightedDigit([...base, first], [11, 10, 9, 8, 7, 6, 5, 4, 3, 2]);
  return `${base.join('')}${first}${second}`;
}

function buildCustomers(rng: Prng, sellers: readonly Seller[]): Customer[] {
  const activeSellers = sellers.filter((s) => s.active && s.code > 102).map((s) => s.code);
  const inactiveSeller = sellers.find((s) => !s.active)?.code ?? null;
  const usedNames = new Set<string>();
  const customers: Customer[] = [];
  let code = CUSTOMER_FIRST_CODE;

  for (let index = 0; index < CUSTOMER_COUNT; index += 1) {
    code += rng.int(1, 4);
    const isCompany = rng.chance(0.78);

    let name: string;
    let tradeName: string;
    for (let attempt = 0; ; attempt += 1) {
      if (isCompany) {
        const root = rng.pick(COMPANY_ROOTS);
        const segment = rng.pick(COMPANY_SEGMENTS);
        tradeName = attempt < 30 ? `${root} ${segment}` : `${root} ${segment} ${index + 1}`;
        name = `${tradeName} ${rng.pick(COMPANY_SUFFIXES)}`;
      } else {
        tradeName = `${rng.pick(GIVEN_NAMES)} ${rng.pick(SURNAMES)}`;
        if (attempt >= 30) tradeName = `${tradeName} ${index + 1}`;
        name = tradeName;
      }
      if (!usedNames.has(name)) break;
    }
    usedNames.add(name);

    const active = !rng.chance(0.08);
    const blocked = active && rng.chance(0.04);

    let sellerCode: number | null;
    const sellerRoll = rng.next();
    if (sellerRoll < 0.06) sellerCode = null;
    else if (sellerRoll < 0.11 && inactiveSeller !== null) sellerCode = inactiveSeller;
    else sellerCode = rng.pick(activeSellers);

    // The fallback table is deliberately never a customer's own table.
    const priceTableCode = rng.weighted<number | null>([
      [DEMO_MAIN_TABLE_CODE, 80],
      [DEMO_DERIVED_TABLE_CODE, 12],
      [null, 8],
    ]);

    const creditLimit = rng.chance(0.12)
      ? null
      : fixedToDecimal(
          Math.max(0, rng.pick(CREDIT_STEPS) + rng.int(-4, 4) * 250 * (rng.chance(0.5) ? 1 : 0)) * 100 +
            (rng.chance(0.2) ? 50 : 0),
          2,
        );

    const document = rng.chance(0.01) ? null : isCompany ? fakeCnpj(index + 1) : fakeCpf(index + 1);

    customers.push({
      code,
      name,
      tradeName,
      document,
      active,
      blocked,
      sellerCode,
      priceTableCode,
      creditLimit,
    });
  }
  return customers;
}

// ---- products -----------------------------------------------------------------------------------

interface GroupSpec {
  readonly name: string;
  readonly items: readonly string[];
  readonly specs: readonly string[];
  readonly units: readonly string[];
  /** Base unit price range in cents. */
  readonly cents: readonly [number, number];
}

const GROUP_FIRST_CODE = 301;
const GROUP_SPECS: readonly GroupSpec[] = [
  { name: 'Fixadores', items: ['Parafuso sextavado', 'Porca sextavada', 'Arruela lisa', 'Parafuso allen', 'Chumbador', 'Rebite de repuxo'], specs: ['M6', 'M8', 'M10', 'M12', 'M16', '1/4"', '3/8"', '1/2"'], units: ['CX', 'PC', 'UN'], cents: [30, 4500] },
  { name: 'Ferramentas manuais', items: ['Chave de fenda', 'Chave combinada', 'Alicate universal', 'Martelo de bola', 'Trena', 'Serra arco'], specs: ['6 mm', '8 mm', '10 mm', '13 mm', '200 mm', '5 m', '300 mm', 'profissional'], units: ['UN', 'PC'], cents: [1500, 25000] },
  { name: 'Abrasivos', items: ['Disco de corte', 'Disco de desbaste', "Lixa d'água", 'Lixa de ferro', 'Rebolo', 'Escova de aço'], specs: ['4.1/2"', '7"', 'grão 80', 'grão 120', 'grão 220', 'grão 400', '9"'], units: ['UN', 'PC', 'CX'], cents: [200, 9000] },
  { name: 'Tintas e solventes', items: ['Tinta esmalte sintético', 'Primer', 'Thinner', 'Verniz', 'Massa corrida', 'Aguarrás'], specs: ['0,9 L', '3,6 L', '18 L', 'branco', 'cinza', 'preto', 'fosco'], units: ['UN', 'CX'], cents: [1800, 35000] },
  { name: 'Elétrica industrial', items: ['Cabo flexível', 'Disjuntor', 'Contator', 'Relé térmico', 'Botoeira', 'Lâmpada LED'], specs: ['1,5 mm²', '2,5 mm²', '4 mm²', '16 A', '25 A', '220 V', '24 V', '40 W'], units: ['M', 'UN', 'PC'], cents: [300, 60000] },
  { name: 'Hidráulica', items: ['Registro de esfera', 'Joelho 90', 'Luva de união', 'Tubo PVC', 'Mangueira trançada', 'Válvula de retenção'], specs: ['1/2"', '3/4"', '1"', '1.1/4"', '2"', '50 mm', '100 mm'], units: ['UN', 'M', 'PC'], cents: [400, 40000] },
  { name: 'EPI', items: ['Luva de raspa', 'Óculos de proteção', 'Protetor auricular', 'Capacete', 'Bota de segurança', 'Máscara PFF2'], specs: ['tam. P', 'tam. M', 'tam. G', 'incolor', 'cinza', 'amarelo'], units: ['PC', 'UN', 'CX'], cents: [500, 18000] },
  { name: 'Rolamentos e correias', items: ['Rolamento rígido', 'Rolamento de rolos', 'Correia em V', 'Correia sincronizada', 'Retentor', 'Mancal'], specs: ['6203', '6204', '6305', 'B60', 'A45', 'HTD 5M', 'SN 507'], units: ['UN', 'PC'], cents: [1500, 90000] },
  { name: 'Soldagem', items: ['Eletrodo revestido', 'Arame MIG', 'Máscara de solda', 'Vareta TIG', 'Bocal para tocha', 'Gás de proteção'], specs: ['2,5 mm', '3,25 mm', '0,8 mm', '1,2 mm', 'classe 6013', 'classe 7018', 'classe 70S'], units: ['KG', 'UN', 'CX'], cents: [2500, 70000] },
  { name: 'Lubrificantes', items: ['Óleo hidráulico', 'Graxa de lítio', 'Óleo lubrificante', 'Desengripante', 'Óleo de corte'], specs: ['ISO 46', 'ISO 68', '20W-50', '1 kg', '500 mL', '5 kg', '20 L'], units: ['UN', 'CX', 'KG'], cents: [1200, 55000] },
  { name: 'Embalagens', items: ['Fita adesiva', 'Filme stretch', 'Caixa de papelão', 'Saco plástico', 'Fita de arquear', 'Etiqueta adesiva'], specs: ['48 mm x 50 m', '500 mm', '40x30x20 cm', '30x40 cm', '12 mm', '100 x 50 mm'], units: ['CX', 'UN', 'KG', 'M'], cents: [300, 20000] },
  { name: 'Chapas e perfis', items: ['Chapa de aço', 'Barra chata', 'Cantoneira', 'Tubo quadrado', 'Barra redonda', 'Perfil U'], specs: ['2 mm', '3 mm', '1/4"', '20x20', '30x30', '1"', '1.1/2"'], units: ['KG', 'M', 'PC', 'UN'], cents: [500, 150000] },
];

const BRANDS = ['Brasten', 'Metalar', 'Torqmax', 'Pratil', 'Vexon', 'Ordena', 'Ferrol', 'Zintex', 'Nortelar', 'Orbitam', 'Kestrel', 'Vitrolex'];
const PRODUCT_COUNT = 400;
const PRODUCT_FIRST_CODE = 70001;

/** Usage codes are a small synthetic set; only `A` and `B` are sellable in the demo configuration. */
const USAGE_WEIGHTS: readonly (readonly [string, number])[] = [
  ['A', 35],
  ['B', 25],
  ['C', 15],
  ['D', 10],
  ['E', 10],
  ['F', 5],
];

interface ProductBuild {
  readonly product: Product;
  /** Base price in 10^-4 currency units. */
  readonly basePrice: number;
}

function buildProducts(rng: Prng): { groups: ProductGroup[]; products: ProductBuild[] } {
  const groups: ProductGroup[] = GROUP_SPECS.map((spec, index) => ({ code: GROUP_FIRST_CODE + index, name: spec.name }));
  const usedDescriptions = new Set<string>();
  const products: ProductBuild[] = [];
  let code = PRODUCT_FIRST_CODE;

  for (let index = 0; index < PRODUCT_COUNT; index += 1) {
    code += rng.int(1, 3);
    const groupIndex = rng.int(0, GROUP_SPECS.length - 1);
    const spec = GROUP_SPECS[groupIndex];
    if (spec === undefined) throw new RangeError('group spec missing');

    let description: string;
    for (let attempt = 0; ; attempt += 1) {
      description = `${rng.pick(spec.items)} ${rng.pick(spec.specs)}`;
      if (attempt >= 20) description = `${description} #${index + 1}`;
      if (!usedDescriptions.has(description)) break;
    }
    usedDescriptions.add(description);

    const brand = rng.chance(0.04) ? null : rng.pick(BRANDS);
    const reference = rng.chance(0.45) ? `REF-${String(rng.int(1, 99999)).padStart(5, '0')}` : null;
    const [minCents, maxCents] = spec.cents;
    const skew = rng.next() ** 2;
    const cents = Math.round(minCents + (maxCents - minCents) * skew);
    // 10% of products carry sub-cent precision (unit prices are numeric(18,6) in storage).
    const basePrice = cents * 100 + (rng.chance(0.1) ? rng.int(1, 99) : 0);

    products.push({
      basePrice,
      product: {
        code,
        description,
        active: !rng.chance(0.07),
        usageCode: rng.weighted(USAGE_WEIGHTS),
        groupCode: GROUP_FIRST_CODE + groupIndex,
        unit: rng.pick(spec.units),
        brand,
        reference,
      },
    });
  }
  return { groups, products };
}

// ---- price tables -------------------------------------------------------------------------------

const VERSION_IDS = {
  [DEMO_MAIN_TABLE_CODE]: { older: 501, effective: 502 },
  [DEMO_DERIVED_TABLE_CODE]: { older: 503, effective: 504 },
  [DEMO_FALLBACK_TABLE_CODE]: { older: 505, effective: 506 },
} as const;

const DERIVED_PERCENT = '15';

function isSellable(product: Product): boolean {
  return product.usageCode !== null && DEMO_SELLABLE_USAGE_CODES.includes(product.usageCode);
}

interface PriceSpec {
  readonly versionId: number;
  /** Multiplier applied to the product's base price, in per-mille. */
  readonly perMille: number;
  readonly coverage: { readonly sellable: number; readonly other: number; readonly inactive: number };
  readonly zeroRate: number;
}

function buildPriceRows(rng: Prng, products: readonly ProductBuild[], spec: PriceSpec): ListPrice[] {
  const rows: ListPrice[] = [];
  for (const { product, basePrice } of products) {
    const probability = !product.active
      ? spec.coverage.inactive
      : isSellable(product)
        ? spec.coverage.sellable
        : spec.coverage.other;
    if (!rng.chance(probability)) continue;
    // Explicit zero rows exist in the ERP and are kept distinct from "no row" (F-42).
    const zero = rng.chance(spec.zeroRate);
    const unitPrice = zero ? '0' : fixedToDecimal(Math.round((basePrice * spec.perMille) / 1000), 4);
    rows.push({ versionId: spec.versionId, productCode: product.code, unitPrice });
  }
  return rows;
}

// ---- assembly -----------------------------------------------------------------------------------

function deepFreeze<T>(value: T): T {
  if (typeof value === 'object' && value !== null && !Object.isFrozen(value)) {
    Object.freeze(value);
    for (const child of Object.values(value)) deepFreeze(child);
  }
  return value;
}

export function generateDemoDataset(seed: number = DEMO_SEED): DemoDataset {
  const rng = new Prng(seed);
  const { sellers, links } = buildSellers();
  const customers = buildCustomers(rng, sellers);
  const { groups, products } = buildProducts(rng);

  const main = VERSION_IDS[DEMO_MAIN_TABLE_CODE];
  const derived = VERSION_IDS[DEMO_DERIVED_TABLE_CODE];
  const fallback = VERSION_IDS[DEMO_FALLBACK_TABLE_CODE];

  const priceTables: PriceTable[] = [
    { code: DEMO_MAIN_TABLE_CODE, name: 'Tabela Balcão (demonstração)', active: true, originTableCode: null, percent: null },
    { code: DEMO_DERIVED_TABLE_CODE, name: 'Tabela Atacado derivada (demonstração)', active: true, originTableCode: DEMO_MAIN_TABLE_CODE, percent: DERIVED_PERCENT },
    { code: DEMO_FALLBACK_TABLE_CODE, name: 'Tabela Especial (demonstração)', active: true, originTableCode: null, percent: null },
  ];
  const priceTableVersions: PriceTableVersion[] = [
    { versionId: main.older, tableCode: DEMO_MAIN_TABLE_CODE, effectiveFrom: DEMO_OLDER_VERSION_FROM },
    { versionId: main.effective, tableCode: DEMO_MAIN_TABLE_CODE, effectiveFrom: DEMO_EFFECTIVE_VERSION_FROM },
    { versionId: derived.older, tableCode: DEMO_DERIVED_TABLE_CODE, effectiveFrom: DEMO_OLDER_VERSION_FROM },
    { versionId: derived.effective, tableCode: DEMO_DERIVED_TABLE_CODE, effectiveFrom: DEMO_EFFECTIVE_VERSION_FROM },
    { versionId: fallback.older, tableCode: DEMO_FALLBACK_TABLE_CODE, effectiveFrom: DEMO_OLDER_VERSION_FROM },
    { versionId: fallback.effective, tableCode: DEMO_FALLBACK_TABLE_CODE, effectiveFrom: DEMO_FALLBACK_EFFECTIVE_FROM },
  ];

  // A derived table has no rows of its own (F-41): its prices are a percentage on the origin table.
  // The mirror stores versions and rows; the derivation rule is not implemented here (S2.3, NEEDS VALIDATION).
  const listPrices: ListPrice[] = [
    ...buildPriceRows(rng, products, {
      versionId: main.older,
      perMille: 940,
      coverage: { sellable: 0.9, other: 0.25, inactive: 0.3 },
      zeroRate: 0.02,
    }),
    ...buildPriceRows(rng, products, {
      versionId: main.effective,
      perMille: 1000,
      coverage: { sellable: 0.93, other: 0.3, inactive: 0 },
      zeroRate: 0.03,
    }),
    ...buildPriceRows(rng, products, {
      versionId: fallback.older,
      perMille: 1020,
      coverage: { sellable: 0.8, other: 0.15, inactive: 0.2 },
      zeroRate: 0.02,
    }),
    ...buildPriceRows(rng, products, {
      versionId: fallback.effective,
      perMille: 1080,
      coverage: { sellable: 0.85, other: 0.2, inactive: 0 },
      zeroRate: 0.03,
    }),
  ];

  for (const row of listPrices) {
    if (canonicalDecimal(row.unitPrice) !== row.unitPrice) throw new RangeError('non-canonical fixture price');
  }

  return deepFreeze({
    sellers,
    sellerManagerLinks: links,
    customers,
    productGroups: groups,
    products: products.map((p) => p.product),
    priceTables,
    priceTableVersions,
    listPrices,
  });
}

let cached: DemoDataset | undefined;

/** The default demo dataset (seed `DEMO_SEED`), generated once per process. Frozen. */
export function getDemoDataset(): DemoDataset {
  cached ??= generateDemoDataset();
  return cached;
}
