// Module: templates — recurring order templates per customer ("Recorrentes"). A template is a saved
// list of (product, quantity) lines: no price, discount, notes or seller. Using one creates an
// independent draft through the normal order path, so there is deliberately no FK to sales_order.
// Limits (50 templates per customer, 500 items per template) are enforced by the service.
import { sql } from 'drizzle-orm';
import {
  check,
  integer,
  numeric,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';
import { account } from './iam.js';

/** Hard ceiling on lines per template (mirrors the service limit; cheap to enforce here). */
export const MAX_TEMPLATE_ITEMS = 500;

export const customerOrderTemplate = pgTable(
  'customer_order_template',
  {
    /** UUIDv7 generated by the application (DATA-1). */
    id: uuid('id').primaryKey(),
    /** Customer code as mirrored (no FK: mirror rows are soft-deleted and owned by another module). */
    customerCode: integer('customer_code').notNull(),
    name: text('name').notNull(),
    createdByAccountId: uuid('created_by_account_id')
      .notNull()
      .references(() => account.id),
    /** Client-generated idempotency key for creation, unique per creating account. */
    clientRequestId: uuid('client_request_id').notNull(),
    /** SHA-256 (hex) of the canonical create payload: same id with another payload is a conflict. */
    requestHash: text('request_hash').notNull(),
    /** Optimistic concurrency counter. */
    version: integer('version').notNull().default(1),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
    /** Soft delete. */
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
  },
  (t) => [
    check(
      'customer_order_template_name_chk',
      sql`${t.name} ~ '[^[:space:]]' and char_length(${t.name}) <= 80`,
    ),
    check('customer_order_template_version_chk', sql`${t.version} >= 1`),
    // Live template names are unique per customer, case-insensitively.
    // Serves: name-collision check on create/replace, and listing a customer's live templates by name.
    uniqueIndex('customer_order_template_customer_name_uq')
      .on(t.customerCode, sql`lower(${t.name})`)
      .where(sql`${t.deletedAt} is null`),
    // Idempotent creation (includes soft-deleted rows, so a replay after delete never re-creates).
    // Serves: POST replay lookup by (account, client request id); also the FK lookup on account.
    uniqueIndex('customer_order_template_account_request_uq').on(
      t.createdByAccountId,
      t.clientRequestId,
    ),
  ],
);

export const customerOrderTemplateItem = pgTable(
  'customer_order_template_item',
  {
    templateId: uuid('template_id')
      .notNull()
      .references(() => customerOrderTemplate.id, { onDelete: 'cascade' }),
    lineNo: integer('line_no').notNull(),
    /** Product code as mirrored (no FK: the product is revalidated when the template is used). */
    productCode: integer('product_code').notNull(),
    /** Quantity precision NEEDS VALIDATION (S2); same shape as sales_order_item.quantity. */
    quantity: numeric('quantity', { precision: 14, scale: 4 }).notNull(),
  },
  (t) => [
    primaryKey({ name: 'customer_order_template_item_pk', columns: [t.templateId, t.lineNo] }),
    check(
      'customer_order_template_item_line_no_chk',
      sql`${t.lineNo} between 1 and ${sql.raw(String(MAX_TEMPLATE_ITEMS))}`,
    ),
    check('customer_order_template_item_quantity_chk', sql`${t.quantity} > 0`),
  ],
);
